
services:

  mysql:
      image: mysql:5.7
      platform: linux/amd64
      labels:
        - "app=kafka-stack"
      ports:
        - "3307:3307"
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: demo
        MYSQL_USER: debezium
        MYSQL_PASSWORD: debezium_pass
      command:
        --gtid-mode=ON
        --log-bin=mysql-bin
        --binlog-format=ROW
        --binlog-row-image=FULL
        --server-id=223344
        --enforce-gtid-consistency=ON


  oracle-xe:
    image: gvenzl/oracle-xe:21
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: MySecurePassword1
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped


volumes:
  oracle-data:
  minio-data:
    driver: local